ALTER TABLE metrics ADD COLUMN gpu_usage REAL NOT NULL DEFAULT 0.0;
ALTER TABLE metrics ADD COLUMN gpu_temp REAL NOT NULL DEFAULT 0.0;
ALTER TABLE metrics ADD COLUMN gpu_vram_used_mb REAL NOT NULL DEFAULT 0.0;